# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20171211_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
