# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'male', '\u7537'), (b'female', '\u5973')], default=b'female', max_length=6),
        ),
    ]
